# frozen_string_literal: true

require "json"

module FairlanesContent
  class Renderer
    def initialize(declarations)
      @declarations = declarations
    end

    def skills = declarations.skills
    def monsters = declarations.monsters
    def statuses = declarations.statuses
    def visuals = declarations.visuals
    def random_combat_skills = declarations.random_combat_skills

    def test_cpp
      skill_rows = skills.map do |skill|
        visual = skill.visual ? visual_cpp(skill) : "std::nullopt"
        <<~CPP
              ExpectedSkill{
                  #{skill_key_cpp(skill)},
                  #{cpp_string(skill.display)},
                  #{skill.learn_chance_percent},
                  #{skill.flee_success_percent},
                  #{skill.random_combat ? "true" : "false"},
                  #{visual},
              },
        CPP
      end.join

      random_skill_rows = random_combat_skills.map do |skill_id|
        "    fl::skills::SkillKey{#{skill_symbol_cpp(skill_id)}},"
      end.join("\n")

      monster_rows = monsters.map do |monster|
        known_skills = monster.known_skills.map { |skill_id| skill_symbol_cpp(skill_id) }
                                    .join(", ")
        <<~CPP
              ExpectedMonster{
                  #{monster_cpp(monster)},
                  #{cpp_string(monster.display)},
                  #{monster.hp},
                  #{monster.mp},
                  #{monster.level || 0},
                  std::array<fl::skills::SkillId, #{monster.known_skills.size}>{#{known_skills}},
                  Pool::#{pool_cpp(monster.pool)},
              },
        CPP
      end.join

      status_rows = statuses.map do |status|
        <<~CPP
              ExpectedStatus{
                  fl::status::StatusId::#{status.cpp_id},
                  #{cpp_string(status.display)},
                  #{cpp_string(status.debug_name)},
                  #{cpp_string(status.component)},
                  #{status.palette_index},
              },
        CPP
      end.join

      skill_tag_sections = skills.map do |skill|
        tag_checks = skill.tags.map do |tag|
          "      REQUIRE(fl::skills::has_tag(skill, #{tag_cpp(tag)}));"
        end.join("\n")
        <<~CPP
            SECTION(#{cpp_string(skill.display)}) {
              const auto skill = #{skill_key_cpp(skill)};
              const auto &definition = fl::skills::definition(skill);
              REQUIRE(definition.execution == #{execution_cpp(skill)});
              REQUIRE(definition.tags.size() == #{skill.tags.size});
        #{tag_checks}
            }
        CPP
      end.join

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include <catch2/catch_test_macros.hpp>

        #include <algorithm>
        #include <array>
        #include <optional>
        #include <span>
        #include <string_view>
        #include <tuple>

        #include "fl/ecs/components/skill_slots.hpp"
        #include "fl/ecs/components/stats.hpp"
        #include "fl/ecs/components/track_xp.hpp"
        #include "fl/grand_central.hpp"
        #include "fl/monsters/monster_kind.hpp"
        #include "fl/monsters/monster_registry.hpp"
        #include "fl/monsters/register_monsters.hpp"
        #include "fl/primitives/encounter_builder.hpp"
        #include "fl/primitives/entity_builder.hpp"
        #include "fl/skills/skill.hpp"
        #include "fl/skills/skill_definition.hpp"
        #include "fl/skills/skill_visuals.hpp"
        #include "fl/generated/status_content.hpp"
        #include "fl/widgets/effects/decal.hpp"

        namespace {

        enum class Pool {
          CommonWoodland,
          RareWoodland,
        };

        struct ExpectedSkill {
          fl::skills::SkillKey skill;
          std::string_view skill_name;
          int learn_chance_percent;
          int flee_success_percent;
          bool random_combat;
          std::optional<fl::widgets::effects::DecalAnimationKind> visual;
        };

        struct ExpectedStatus {
          fl::status::StatusId status;
          std::string_view display_name;
          std::string_view debug_name;
          std::string_view component_name;
          int palette_index;
        };

        template <std::size_t KnownSkillCount>
        struct ExpectedMonster {
          fl::monster::MonsterKind monster;
          std::string_view monster_name;
          int hp;
          int mp;
          int level;
          std::array<fl::skills::SkillId, KnownSkillCount> known_skills;
          Pool pool;
        };

        constexpr std::array<ExpectedSkill, #{skills.size}> kExpectedSkills{{
        #{skill_rows}
        }};

        constexpr std::array<fl::skills::SkillKey, #{random_combat_skills.size}> kExpectedRandomCombatSkills{{
        #{random_skill_rows}
        }};

        constexpr std::array<ExpectedStatus, #{statuses.size}> kExpectedStatuses{{
        #{status_rows}
        }};

        constexpr auto kExpectedMonsters = std::tuple{
        #{monster_rows}
        };

        template <class Fn> void for_each_expected_monster(Fn &&fn) {
          std::apply([&](const auto &...monster) { (fn(monster), ...); },
                     kExpectedMonsters);
        }

        } // namespace

        TEST_CASE("Generated skill declarations mirror runtime definitions",
                  "[generated][content][skills]") {
          for (const auto &expected : kExpectedSkills) {
            CAPTURE(expected.skill_name);
            REQUIRE(fl::skills::name(expected.skill) == expected.skill_name);
            REQUIRE(fl::skills::learn_chance_percent(expected.skill) ==
                    expected.learn_chance_percent);
            REQUIRE(fl::skills::definition(expected.skill).flee_success_percent ==
                    expected.flee_success_percent);
            REQUIRE(fl::skills::definition(expected.skill).decal_animation ==
                    expected.visual);
          }
        }

        TEST_CASE("Generated skill declarations satisfy content invariants",
                  "[generated][content][skills][invariants]") {
          REQUIRE(fl::skills::all_definitions().size() == kExpectedSkills.size());
          REQUIRE(std::ranges::equal(fl::skills::random_combat_skills(),
                                     kExpectedRandomCombatSkills));

          for (std::size_t i = 0; i < kExpectedSkills.size(); ++i) {
            const auto &skill = kExpectedSkills[i];
            CAPTURE(skill.skill_name);
            REQUIRE_FALSE(skill.skill_name.empty());
            REQUIRE(skill.learn_chance_percent >= 0);
            REQUIRE(skill.learn_chance_percent <= 100);
            REQUIRE(skill.flee_success_percent >= 0);
            REQUIRE(skill.flee_success_percent <= 100);
            if (fl::skills::definition(skill.skill).execution !=
                fl::skills::SkillExecutionKind::Flee) {
              REQUIRE(skill.flee_success_percent == 0);
            }

            for (std::size_t j = i + 1; j < kExpectedSkills.size(); ++j) {
              REQUIRE(skill.skill.base != kExpectedSkills[j].skill.base);
            }
          }

          const auto random_combat_skills = fl::skills::random_combat_skills();
          REQUIRE_FALSE(std::find(random_combat_skills.begin(),
                                  random_combat_skills.end(),
                                  fl::skills::SkillKey{fl::skills::SkillId::Observe}) !=
                        random_combat_skills.end());
        }

        TEST_CASE("Generated skill tags and execution kinds mirror runtime definitions",
                  "[generated][content][skills][tags]") {
        #{skill_tag_sections}
        }

        TEST_CASE("Generated status declarations mirror runtime metadata",
                  "[generated][content][statuses]") {
          REQUIRE(fl::status::generated_content::all_statuses().size() ==
                  kExpectedStatuses.size());

          for (const auto &expected : kExpectedStatuses) {
            CAPTURE(expected.display_name);
            const auto metadata =
                fl::status::generated_content::metadata(expected.status);
            REQUIRE(metadata.display_name == expected.display_name);
            REQUIRE(metadata.debug_name == expected.debug_name);
            REQUIRE(metadata.component_name == expected.component_name);
            REQUIRE(metadata.palette_index == expected.palette_index);
          }
        }

        TEST_CASE("Generated monster declarations mirror runtime registry",
                  "[generated][content][monsters]") {
          fl::monster::register_all_monsters();
          REQUIRE(fl::monster::monster_registry().size() == #{monsters.size});

          fl::GrandCentral gc{1, 1, 1};
          auto account_ctx = gc.account_context(0);
          auto party_ctx = account_ctx.party_context(0);
          auto build_ctx = party_ctx.build_context();

          for_each_expected_monster([&](const auto &expected) {
            CAPTURE(expected.monster_name);
            auto &registry = fl::monster::monster_registry();
            const auto found = registry.find(expected.monster);
            REQUIRE(found != registry.end());
            REQUIRE(found->second.known_skills.size() ==
                    expected.known_skills.size());
            for (const auto skill : expected.known_skills) {
              REQUIRE(std::find(found->second.known_skills.begin(),
                                found->second.known_skills.end(),
                                skill) != found->second.known_skills.end());
            }

            const auto entity =
                fl::primitives::EntityBuilder(build_ctx).monster(expected.monster).build();
            const auto &stats =
                party_ctx.reg().get<fl::ecs::components::Stats>(entity);
            REQUIRE(stats.name_ == expected.monster_name);
            REQUIRE(stats.hp_ == expected.hp);
            REQUIRE(stats.max_hp_ == expected.hp);
            REQUIRE(stats.mp_ == expected.mp);
            if (expected.level > 0) {
              const auto &xp =
                  party_ctx.reg().get<fl::ecs::components::TrackXP>(entity);
              REQUIRE(xp.level_ == expected.level);
            }
            const auto &slots =
                party_ctx.reg().get<fl::ecs::components::SkillSlots>(entity);
            for (const auto skill : expected.known_skills) {
              REQUIRE(slots.knows(skill));
            }
          });
        }

        TEST_CASE("Generated encounter pool declarations mirror runtime pools",
                  "[generated][content][encounter_builder]") {
          for_each_expected_monster([](const auto &expected) {
            CAPTURE(expected.monster_name);
            if (expected.pool == Pool::RareWoodland) {
              const auto pool = fl::primitives::EncounterBuilder::rare_woodland();
              REQUIRE(std::find(pool.begin(), pool.end(), expected.monster) !=
                      pool.end());
            } else {
              const auto pool = fl::primitives::EncounterBuilder::common_woodland();
              REQUIRE(std::find(pool.begin(), pool.end(), expected.monster) !=
                      pool.end());
            }
          });
        }
      CPP
    end

    def skill_content_hpp
      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        #include <span>

        #include "fl/skills/skill_definition.hpp"

        namespace fl::skills::generated_content {

        std::span<const SkillDefinition *const> all_definitions() noexcept;

        } // namespace fl::skills::generated_content
      CPP
    end

    def skill_ids_hpp
      rows = skills.map { |skill| "  #{skill.cpp_id}," }.join("\n")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        namespace fl::skills {

        enum class SkillId {
        #{rows}
        };

        } // namespace fl::skills
      CPP
    end

    def skill_content_cpp
      includes = skills.map do |skill|
        "#include \"fl/generated/skills/#{skill.id}.hpp\""
      end.join("\n")
      definition_pointer_rows = skills.map do |skill|
        "    &generated_content::detail::k#{skill.cpp_id}Definition,"
      end.join("\n")

      random_skill_rows = random_combat_skills.map do |skill_id|
        "    fl::skills::SkillKey{#{skill_symbol_cpp(skill_id)}},"
      end.join("\n")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include "fl/generated/skill_content.hpp"

        #{includes}

        #include <array>
        #include <span>

        namespace fl::skills {
        namespace {

        constexpr std::array<const SkillDefinition *, #{skills.size}> kSkillDefinitions{{
        #{definition_pointer_rows}
        }};

        constexpr std::array<SkillKey, #{random_combat_skills.size}> kRandomCombatSkills{{
        #{random_skill_rows}
        }};

        } // namespace

        std::span<const SkillKey> random_combat_skills() noexcept {
          return {kRandomCombatSkills.data(), kRandomCombatSkills.size()};
        }

        namespace generated_content {

        std::span<const SkillDefinition *const> all_definitions() noexcept {
          return {kSkillDefinitions.data(), kSkillDefinitions.size()};
        }

        } // namespace generated_content
        } // namespace fl::skills
      CPP
    end

    def skill_entry_hpp(skill)
      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        #include "fl/skills/skill_definition.hpp"

        namespace fl::skills::generated_content::detail {

        extern const SkillDefinition k#{skill.cpp_id}Definition;

        } // namespace fl::skills::generated_content::detail
      CPP
    end

    def skill_entry_cpp(skill)
      tags = skill.tags.map { |tag| tag_cpp(tag) }.join(", ")
      visual = skill.visual ? visual_cpp(skill) : "std::nullopt"

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include "fl/generated/skills/#{skill.id}.hpp"

        #include <array>
        #include <optional>
        #include <span>

        namespace fl::skills::generated_content::detail {
        namespace {

        constexpr std::array k#{skill.cpp_id}Tags{#{tags}};

        } // namespace

        const SkillDefinition k#{skill.cpp_id}Definition{
            #{skill_key_cpp(skill)},
            #{cpp_string(skill.display)},
            std::span<const SkillTag>{k#{skill.cpp_id}Tags.data(),
                                      k#{skill.cpp_id}Tags.size()},
            #{skill.learn_chance_percent},
            #{skill.flee_success_percent},
            #{execution_cpp(skill)},
            #{visual},
        };

        } // namespace fl::skills::generated_content::detail
      CPP
    end

    def status_content_hpp
      rows = statuses.map { |status| "  #{status.cpp_id}," }.join("\n")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        #include <span>
        #include <string_view>

        namespace fl::status {

        enum class StatusId {
        #{rows}
        };

        struct StatusMetadata {
          StatusId id;
          std::string_view display_name;
          std::string_view debug_name;
          std::string_view component_name;
          int palette_index;
        };

        namespace generated_content {

        StatusMetadata metadata(StatusId status) noexcept;
        std::span<const StatusMetadata> all_statuses() noexcept;

        } // namespace generated_content
        } // namespace fl::status
      CPP
    end

    def status_content_cpp
      status_rows = statuses.map do |status|
        <<~CPP
            StatusMetadata{
                StatusId::#{status.cpp_id},
                #{cpp_string(status.display)},
                #{cpp_string(status.debug_name)},
                #{cpp_string(status.component)},
                #{status.palette_index},
            },
        CPP
      end.join

      status_cases = statuses.each_with_index.map do |status, index|
        <<~CPP
            case StatusId::#{status.cpp_id}:
              return kStatuses[#{index}];
        CPP
      end.join

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include "fl/generated/status_content.hpp"

        #include <array>
        #include <span>
        #include <string_view>

        namespace fl::status::generated_content {
        namespace {

        constexpr std::array<StatusMetadata, #{statuses.size}> kStatuses{{
        #{status_rows}
        }};

        } // namespace

        StatusMetadata metadata(StatusId status) noexcept {
          switch (status) {
        #{status_cases}
          }
          return StatusMetadata{status, "", "", "", 0};
        }

        std::span<const StatusMetadata> all_statuses() noexcept {
          return {kStatuses.data(), kStatuses.size()};
        }

        } // namespace fl::status::generated_content
      CPP
    end

    def monster_content_hpp
      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        #include <span>
        #include <string_view>

        #include "fl/monsters/monster_kind.hpp"
        #include "fl/skills/skill.hpp"

        namespace fl::monster::generated_content {

        struct MonsterStats {
          std::string_view display_name;
          int hp;
          int mp;
          int level;
        };

        MonsterStats stats(MonsterKind kind) noexcept;
        std::span<const fl::skills::SkillId> known_skills(MonsterKind kind) noexcept;
        std::span<const MonsterKind> common_woodland() noexcept;
        std::span<const MonsterKind> rare_woodland() noexcept;

        } // namespace fl::monster::generated_content
      CPP
    end

    def monster_kinds_hpp
      rows = monsters.map { |monster| "  #{monster.cpp_id}," }.join("\n")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        namespace fl::monster {

        enum class MonsterKind {
        #{rows}
        };

        } // namespace fl::monster
      CPP
    end

    def monster_content_cpp
      includes = monsters.map do |monster|
        "#include \"fl/generated/monsters/#{monster.id}.hpp\""
      end.join("\n")

      stat_cases = monsters.map do |monster|
        <<~CPP
          case MonsterKind::#{monster.cpp_id}:
            return detail::#{monster.cpp_id}Stats();
        CPP
      end.join

      known_skill_cases = monsters.map do |monster|
        <<~CPP
          case MonsterKind::#{monster.cpp_id}:
            return detail::#{monster.cpp_id}KnownSkills();
        CPP
      end.join

      common_rows = monsters.select { |monster| monster.pool == :common_woodland }.map do |monster|
        "    #{monster_cpp(monster)},"
      end.join("\n")

      rare_rows = monsters.select { |monster| monster.pool == :rare_woodland }.map do |monster|
        "    #{monster_cpp(monster)},"
      end.join("\n")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include "fl/generated/monster_content.hpp"

        #{includes}

        #include <array>
        #include <span>
        #include <string_view>

        #include "fl/monsters/monster_kind.hpp"
        #include "fl/skills/skill.hpp"

        namespace fl::monster::generated_content {
        namespace {

        constexpr std::array<MonsterKind, #{monsters.count { |monster| monster.pool == :common_woodland }}> kCommonWoodland{{
        #{common_rows}
        }};

        constexpr std::array<MonsterKind, #{monsters.count { |monster| monster.pool == :rare_woodland }}> kRareWoodland{{
        #{rare_rows}
        }};

        } // namespace

        MonsterStats stats(MonsterKind kind) noexcept {
          switch (kind) {
        #{stat_cases}
          }
          return MonsterStats{"", 0, 0, 0};
        }

        std::span<const fl::skills::SkillId> known_skills(MonsterKind kind) noexcept {
          switch (kind) {
        #{known_skill_cases}
          }
          return {};
        }

        std::span<const MonsterKind> common_woodland() noexcept {
          return {kCommonWoodland.data(), kCommonWoodland.size()};
        }

        std::span<const MonsterKind> rare_woodland() noexcept {
          return {kRareWoodland.data(), kRareWoodland.size()};
        }

        } // namespace fl::monster::generated_content
      CPP
    end

    def monster_entry_hpp(monster)
      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        #include <span>

        #include "fl/generated/monster_content.hpp"
        #include "fl/skills/skill.hpp"

        namespace fl::monster::generated_content::detail {

        const MonsterStats &#{monster.cpp_id}Stats() noexcept;
        std::span<const fl::skills::SkillId> #{monster.cpp_id}KnownSkills() noexcept;

        } // namespace fl::monster::generated_content::detail
      CPP
    end

    def monster_entry_cpp(monster)
      known_skills = monster.known_skills.map { |skill_id| skill_symbol_cpp(skill_id) }.join(", ")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include "fl/generated/monsters/#{monster.id}.hpp"

        #include <array>
        #include <span>

        #include "fl/skills/skill.hpp"

        namespace fl::monster::generated_content::detail {
        namespace {

        constexpr std::array k#{monster.cpp_id}KnownSkillsData{#{known_skills}};
        constexpr MonsterStats k#{monster.cpp_id}StatsData{
            #{cpp_string(monster.display)},
            #{monster.hp},
            #{monster.mp},
            #{monster.level || 0},
        };

        } // namespace

        const MonsterStats &#{monster.cpp_id}Stats() noexcept {
          return k#{monster.cpp_id}StatsData;
        }

        std::span<const fl::skills::SkillId> #{monster.cpp_id}KnownSkills() noexcept {
          return {k#{monster.cpp_id}KnownSkillsData.data(),
                  k#{monster.cpp_id}KnownSkillsData.size()};
        }

        } // namespace fl::monster::generated_content::detail
      CPP
    end

    def monster_registration_hpp
      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #pragma once

        namespace fl::monster::generated_content {

        void register_monster_archetypes();

        } // namespace fl::monster::generated_content
      CPP
    end

    def monster_registration_cpp
      registration_rows = monsters.map do |monster|
        <<~CPP
            register_monster(MonsterKind::#{monster.cpp_id}, [](EntityBuilder &builder) {
              apply_monster_stats(builder, MonsterKind::#{monster.cpp_id});
            });
        CPP
      end.join("\n")

      <<~CPP
        // Generated by scripts/fairlanes_content_codegen.rb. Do not edit by hand.
        #include "fl/generated/monster_registration.hpp"

        #include "fl/monsters/apply_monster_stats.hpp"
        #include "fl/monsters/monster_kind.hpp"
        #include "fl/monsters/monster_registry.hpp"
        #include "fl/primitives/entity_builder.hpp"

        namespace fl::monster::generated_content {

        void register_monster_archetypes() {
        #{registration_rows}
        }

        } // namespace fl::monster::generated_content
      CPP
    end

    def balance_report
      skill_metadata_by_id = skills.to_h { |skill| [skill.id, skill] }
      monsters_by_skill = monsters_by_skill_map

      lines = [
        "# Fairlanes Generated Content Balance Report",
        "",
        "Generated by `scripts/fairlanes_content_codegen.rb`.",
        "",
        "Generated artifacts currently provide runtime skill metadata C++, status metadata C++, monster topology metadata C++, monster registration glue, and review reports.",
        "",
        "## Summary",
        "",
        "| Projection | Count | Source of truth |",
        "| --- | ---: | --- |",
        "| Skill definitions | #{skills.size} | Ruby DSL generated C++ `SkillDefinition` table |",
        "| Random combat skills | #{random_combat_skills.size} | Ruby DSL generated C++ random combat table |",
        "| Status declarations | #{statuses.size} | Ruby DSL generated C++ status metadata table |",
        "| Monster declarations | #{monsters.size} | Ruby DSL generated C++ monster topology table |",
        "| Common woodland monsters | #{monsters.count { |monster| monster.pool == :common_woodland }} | Ruby DSL generated C++ encounter pool |",
        "| Rare woodland monsters | #{monsters.count { |monster| monster.pool == :rare_woodland }} | Ruby DSL generated C++ encounter pool |",
        "",
        "## Skill Metadata",
        "",
        "| Skill | C++ ID | Learn chance | Flee success | Random combat | Execution | Visual | Monsters | Shape |",
        "| --- | --- | ---: | ---: | --- | --- | --- | --- | --- |"
      ]

      skills.each do |skill|
        lines << [
          skill.display,
          skill.cpp_id,
          skill.learn_chance_percent,
          skill.flee_success_percent,
          skill.random_combat ? "yes" : "no",
          skill.execution,
          skill.visual ? visuals.fetch(skill.visual) : "",
          monsters_by_skill[skill.id].map(&:display).join(", "),
          skill.declarative_shape
        ].join(" | ").then { |row| "| #{row} |" }
      end

      lines.concat [
        "",
        "## Status Metadata",
        "",
        "| Status | C++ ID | Component | Debug name | Palette index |",
        "| --- | --- | --- | --- | ---: |"
      ]

      statuses.each do |status|
        lines << [
          status.display,
          status.cpp_id,
          status.component,
          status.debug_name,
          status.palette_index
        ].join(" | ").then { |row| "| #{row} |" }
      end

      lines.concat [
        "",
        "## Monster Topology",
        "",
        "| Monster | C++ ID | HP | MP | Level | Known skills | Pool |",
        "| --- | --- | ---: | ---: | ---: | --- | --- |"
      ]

      monsters.each do |monster|
        lines << [
          monster.display,
          monster.cpp_id,
          monster.hp,
          monster.mp,
          monster.level || "",
          monster.known_skills.map { |skill| skill_metadata_by_id.fetch(skill).display }.join(", "),
          monster.pool
        ].join(" | ").then { |row| "| #{row} |" }
      end

      lines.concat [
        "",
        "## Decal Skill Projection",
        "",
        "| Skill | Monster | Visual | Tags |",
        "| --- | --- | --- | --- |"
      ]

      skills.select(&:visual).each do |skill|
        lines << [
          skill.display,
          monsters_by_skill[skill.id].map(&:display).join(", "),
          visuals.fetch(skill.visual),
          skill.tags.join(", ")
        ].join(" | ").then { |row| "| #{row} |" }
      end

      "#{lines.join("\n")}\n"
    end

    def effect_gallery
      monsters_by_skill = monsters_by_skill_map
      visual_skills = skills.select(&:visual).group_by(&:visual)

      lines = [
        "# Fairlanes Generated Effect Gallery Metadata",
        "",
        "Generated by `scripts/fairlanes_content_codegen.rb`.",
        "",
        "This is review metadata for the handwritten decal renderer and generated skill metadata.",
        "",
        "| Visual | Skills | Monsters | Tags | Shape |",
        "| --- | --- | --- | --- | --- |"
      ]

      visuals.each do |visual_id, cpp_id|
        visual_skill_rows = visual_skills.fetch(visual_id, [])
        next if visual_skill_rows.empty?

        visual_monsters = visual_skill_rows.flat_map { |skill| monsters_by_skill[skill.id] }.uniq
        tags = visual_skill_rows.flat_map(&:tags).uniq
        shapes = visual_skill_rows.map(&:declarative_shape).uniq

        lines << [
          cpp_id,
          visual_skill_rows.map(&:display).join(", "),
          visual_monsters.map(&:display).join(", "),
          tags.join(", "),
          shapes.join(", ")
        ].join(" | ").then { |row| "| #{row} |" }
      end

      lines.concat [
        "",
        "## Skill Entries",
        "",
        "| Skill | Visual | Execution | Monsters | Tags |",
        "| --- | --- | --- | --- | --- |"
      ]

      skills.select(&:visual).each do |skill|
        lines << [
          skill.display,
          visuals.fetch(skill.visual),
          skill.execution,
          monsters_by_skill[skill.id].map(&:display).join(", "),
          skill.tags.join(", ")
        ].join(" | ").then { |row| "| #{row} |" }
      end

      "#{lines.join("\n")}\n"
    end

    def manifest
      {
        "schema_version" => 1,
        "source" => "scripts/fairlanes_content_declarations.rb",
        "runtime_authority" => "Ruby DSL generated C++ skill metadata, status metadata, monster known-skill metadata, encounter pool tables, and monster registration glue; handwritten C++ skill/status behavior and monster construction primitives",
        "visuals" => visuals.map do |id, cpp_id|
          { "id" => id.to_s, "cpp_id" => cpp_id }
        end,
        "statuses" => statuses.map do |status|
          {
            "id" => status.id.to_s,
            "cpp_id" => status.cpp_id,
            "display" => status.display,
            "debug_name" => status.debug_name,
            "component" => status.component,
            "palette_index" => status.palette_index
          }
        end,
        "skills" => skills.map do |skill|
          {
            "id" => skill.id.to_s,
            "cpp_id" => skill.cpp_id,
            "display" => skill.display,
            "learn_chance_percent" => skill.learn_chance_percent,
            "flee_success_percent" => skill.flee_success_percent,
            "random_combat" => skill.random_combat,
            "execution" => skill.execution.to_s,
            "visual" => skill.visual&.to_s,
            "tags" => skill.tags.map(&:to_s),
            "declarative_shape" => skill.declarative_shape.to_s
          }
        end,
        "random_combat_skills" => random_combat_skills.map(&:to_s),
        "monsters" => monsters.map do |monster|
          {
            "id" => monster.id.to_s,
            "cpp_id" => monster.cpp_id,
            "display" => monster.display,
            "hp" => monster.hp,
            "mp" => monster.mp,
            "level" => monster.level,
            "known_skills" => monster.known_skills.map(&:to_s),
            "pool" => monster.pool.to_s
          }
        end
      }.then { |data| "#{JSON.pretty_generate(data)}\n" }
    end

    def manifest_schema
      string_type = { "type" => "string", "minLength" => 1 }
      percent_type = { "type" => "integer", "minimum" => 0, "maximum" => 100 }

      schema = {
        "$schema" => "https://json-schema.org/draft/2020-12/schema",
        "$id" => "https://fairlanes.local/generated/content_manifest.schema.json",
        "title" => "Fairlanes Generated Content Manifest",
        "type" => "object",
        "additionalProperties" => false,
        "required" => %w[schema_version source runtime_authority visuals statuses skills random_combat_skills monsters],
        "properties" => {
          "schema_version" => { "const" => 1 },
          "source" => string_type,
          "runtime_authority" => string_type,
          "visuals" => array_schema(%w[id cpp_id], { "id" => string_type, "cpp_id" => string_type }),
          "statuses" => array_schema(
            %w[id cpp_id display debug_name component palette_index],
            {
              "id" => string_type,
              "cpp_id" => string_type,
              "display" => string_type,
              "debug_name" => string_type,
              "component" => string_type,
              "palette_index" => { "type" => "integer", "minimum" => 0, "maximum" => 31 }
            }
          ),
          "skills" => array_schema(
            %w[id cpp_id display learn_chance_percent flee_success_percent random_combat execution visual tags declarative_shape],
            {
              "id" => string_type,
              "cpp_id" => string_type,
              "display" => string_type,
              "learn_chance_percent" => percent_type,
              "flee_success_percent" => percent_type,
              "random_combat" => { "type" => "boolean" },
              "execution" => string_type,
              "visual" => { "type" => %w[string null] },
              "tags" => { "type" => "array", "minItems" => 1, "items" => string_type },
              "declarative_shape" => string_type
            }
          ),
          "random_combat_skills" => { "type" => "array", "items" => string_type },
          "monsters" => array_schema(
            %w[id cpp_id display hp mp level known_skills pool],
            {
              "id" => string_type,
              "cpp_id" => string_type,
              "display" => string_type,
              "hp" => { "type" => "integer", "minimum" => 1 },
              "mp" => { "type" => "integer", "minimum" => 0 },
              "level" => { "type" => %w[integer null], "minimum" => 1 },
              "known_skills" => { "type" => "array", "minItems" => 1, "items" => string_type },
              "pool" => string_type
            }
          )
        }
      }

      "#{JSON.pretty_generate(schema)}\n"
    end

    private

    attr_reader :declarations

    def cpp_string(value)
      value.inspect
    end

    def skill_id_cpp(skill)
      "fl::skills::SkillId::#{skill.cpp_id}"
    end

    def skill_key_cpp(skill)
      "fl::skills::SkillKey{#{skill_id_cpp(skill)}}"
    end

    def skill_symbol_cpp(skill_id)
      skill = skills.find { |candidate| candidate.id == skill_id }
      raise "unknown skill #{skill_id}" unless skill

      skill_id_cpp(skill)
    end

    def monster_cpp(monster)
      "fl::monster::MonsterKind::#{monster.cpp_id}"
    end

    def visual_cpp(skill)
      "fl::widgets::effects::DecalAnimationKind::#{visuals.fetch(skill.visual)}"
    end

    def cpp_enum_name(id)
      id.to_s.split("_").map(&:capitalize).join
    end

    def execution_cpp(skill)
      "fl::skills::SkillExecutionKind::#{cpp_enum_name(skill.execution)}"
    end

    def tag_cpp(tag)
      "fl::skills::SkillTag::#{cpp_enum_name(tag)}"
    end

    def pool_cpp(pool)
      pool == :rare_woodland ? "RareWoodland" : "CommonWoodland"
    end

    def monsters_by_skill_map
      Hash.new { |hash, key| hash[key] = [] }.tap do |result|
        monsters.each do |monster|
          monster.known_skills.each { |skill| result[skill] << monster }
        end
      end
    end

    def array_schema(required, properties)
      {
        "type" => "array",
        "items" => {
          "type" => "object",
          "additionalProperties" => false,
          "required" => required,
          "properties" => properties
        }
      }
    end
  end
end
