#include "hero_names.hpp"

std::vector<std::string> hero_names{
    "Alderion",           "Bramblethorn",       "Cyran Vale",
    "Dorn Halberd",       "Elaric Vane",        "Fenn Ashwalker",
    "Garric Stone",       "Halden Crest",       "Irwan Brightblade",
    "Joran Thatch",       "Kaelen Ridge",       "Lira Dawnstar",
    "Maelis Thorn",       "Noren Flint",        "Orick Vale",
    "Perrin Frost",       "Quen Hollow",        "Rurik Iron",
    "Sylas Greymantle",   "Tavian Holt",        "Ulric Marsh",
    "Varen Hollowborn",   "Wystan Gale",        "Xaro Windcutter",
    "Yoren Kestrel",      "Zarek Ironwind",

    "Astra Wyn",          "Branik Forge",       "Caelis Thorn",
    "Dorian Hales",       "Esmira Locke",       "Fenric Hollow",
    "Galwyn Ash",         "Hedra Vale",         "Ismere Thorne",
    "Jasker Flint",       "Kendra Voss",        "Lorian Sharpe",
    "Merris Gale",        "Nalia Crest",        "Orren Vale",
    "Perin Ash",          "Quessa Dawn",        "Riven Talon",
    "Sera Wilding",       "Tavris Ember",       "Ulra Greydawn",
    "Vexa Thorn",         "Wendel Frost",       "Xanna Kestrel",
    "Ysmir Black",        "Zanna Hollow",

    "Amon Farrow",        "Brax Ironthorn",     "Calla Bright",
    "Drevin Storm",       "Elias Moor",         "Fiora Ashen",
    "Galen Voss",         "Hawke Bramble",      "Ilra Starlace",
    "Jorren Crest",       "Kira Wildrose",      "Lennox Vale",
    "Maera Frost",        "Nivra Emberfall",    "Oland Thorne",
    "Pyria Vale",         "Quillan Moor",       "Rasha Flint",
    "Sorin Gale",         "Talia Drear",        "Ulven Darkwater",
    "Varra Sky",          "Wynna Storm",        "Xaro Flint",
    "Ylric Thorne",       "Zoren Crest",

    "Aeris Thornblade",   "Berrin Strider",     "Caldor Shale",
    "Derris Wyrmson",     "Elwyn Tallow",       "Faela Crestwind",
    "Garen Vint",         "Havric Shadow",      "Ilyra Dawncrest",
    "Jorek Blade",        "Korrin Fell",        "Lysa Greengate",
    "Merrik Stonebow",    "Nierra Wyld",        "Orric Ashen",
    "Pevrin Moss",        "Quarra Shade",       "Rendal Forge",
    "Syrra Flameborn",    "Tovin Marsh",        "Udra Vale",
    "Varrik Steel",       "Westra Longstride",  "Xyren Tallwind",
    "Ylanna Crestborn",   "Zevran Holt",

    "Arden Wyke",         "Belyn Starborn",     "Cyrus Embersmith",
    "Dalen Ford",         "Eldrin Mossgate",    "Feryn Skytamer",
    "Galdor Icebrand",    "Harven Brine",       "Isran Winter",
    "Jaspen Thornwright", "Kassira Nightbloom", "Leoric Dawnsend",
    "Mira Talewind",      "Nerran Frostshield", "Orris Galeheart",
    "Prynn Valehammer",   "Quilan Shadecrest",  "Ryder Blackthorn",
    "Soren Marshwind",    "Tyra Flintblade",    "Ulmar Stonecrest",
    "Vesper Wren",        "Warrin Ashbreaker",  "Xanor Hollowstar",
    "Ysolde Greymoss",    "Zarik Stormbriar",

    "Ari Thornwall",      "Boran Vintner",      "Cerys Dawnbow",
    "Drax Hollowforge",   "Eylon Frostfall",    "Faris Embercut",
    "Granth Valehelm",    "Hedra Stonesong",    "Isolde Varr",
    "Jorik Fen",          "Kenna Flintmark",    "Lorin Ashstream",
    "Maelis Thornrose",   "Naros Embermark",    "Orrin Gleam",
    "Pryla Crestbloom",   "Quenn Tallspire",    "Rothan Moorwind",
    "Selene Windwright",  "Toran Duskhall",     "Ullis Longhail",
    "Vexmar Thornfield",  "Wynn Starcrest",     "Xerin Wildmark",
    "Ylwin Moorcrest",    "Zathar Bladewind",

    "Aren Mossborn",      "Brask Halestone",    "Cinder Valk",
    "Dorian Flintmark",   "Evela Stormwright",  "Fennic Dawnspear",
    "Garron Marshfell",   "Hesper Thornstar",   "Ismir Frostsong",
    "Jexa Hollowwind",    "Kaerin Sable",       "Lyris Emberwood",
    "Maelor Fenridge",    "Norik Valecrest",    "Ostra Wildthorn",
    "Paerin Ashbriar",    "Quill Thornfield",   "Ryn Ashwalker",
    "Syla Marshrose",     "Tovren Stonebrand",  "Uska Embercut",
    "Variel Dawnflower",  "Wren Thornridge",    "Xevra Shadowfall",
    "Ylric Emberstream",  "Zyra Stormcut"};
